language: objective-c
osx_image: xcode7.2
notifications:
  slack:
    rooms:
      secure: h7uAIunnYkJCqdpipmBl9h0nkDJ3R8iGvhBcUM0TUDNZjoaFfxwZ2b0b2Lt6LOY5Z3evJVjdXJUWnefRDLpJN/QqVtSSMOdXsLgkCoZSs++XZwf/vB4aCyLbzYAqNg6S9lNPKXXylLimUKK+Qcjf8SYNT3ydsop5wbGWPYtf4f0l8zwYGqbi+DZVD4YaAATuzosEnYQda2xGo8aQmSJy3WdSG+MzY6XKA+XCs5mROxtBLRBUD2ijefuZp0EtiqmuitwOsJNO0GBDb3IRSJ8Ko2BOT0yccnd7I5PoX4MJPL+uwxwBXrAk0EkUP4wZgyK5LL6Gau0/8gEILlTHxXMWvcDPomQCPoSDxG7sA7bJuZ8eoUj6B8w/X8zZ3Nt22qajM/NGNMWSt3e+qbW5nCy+Fa2a6YywIIa49xKOFJTLPQ4phWBjyeKvZXdsxg66HihqeBVgcEXHHLWKTCeQXvp0j/eQEQYznnPtuvL4DQS8YALCywo548/XjhmZOiWYOHmXyO2oURfAj3COHR63TpCFD0q0JPbO1LFT9HFiMQoTh2gGsXXQNUs/I9Tywa3dfeq8P1UEy5IshUTLGbOOFexdwfjO513sdwT8ngT9CRz+myZQAuBq3MrZy/RlvfPupQN0dqEfaR7FELl25mJnYuQ2gAIm4TsPWlBGzaU5BlCwWeA=
script: xctool -workspace RPValidationKit.xcworkspace -scheme 'RPValidationKit' -sdk
  iphonesimulator9.2 -arch x86_64 build test
