language: objective-c
osx_image: xcode8.1
notifications:
  slack:
    rooms:
      secure: h7uAIunnYkJCqdpipmBl9h0nkDJ3R8iGvhBcUM0TUDNZjoaFfxwZ2b0b2Lt6LOY5Z3evJVjdXJUWnefRDLpJN/QqVtSSMOdXsLgkCoZSs++XZwf/vB4aCyLbzYAqNg6S9lNPKXXylLimUKK+Qcjf8SYNT3ydsop5wbGWPYtf4f0l8zwYGqbi+DZVD4YaAATuzosEnYQda2xGo8aQmSJy3WdSG+MzY6XKA+XCs5mROxtBLRBUD2ijefuZp0EtiqmuitwOsJNO0GBDb3IRSJ8Ko2BOT0yccnd7I5PoX4MJPL+uwxwBXrAk0EkUP4wZgyK5LL6Gau0/8gEILlTHxXMWvcDPomQCPoSDxG7sA7bJuZ8eoUj6B8w/X8zZ3Nt22qajM/NGNMWSt3e+qbW5nCy+Fa2a6YywIIa49xKOFJTLPQ4phWBjyeKvZXdsxg66HihqeBVgcEXHHLWKTCeQXvp0j/eQEQYznnPtuvL4DQS8YALCywo548/XjhmZOiWYOHmXyO2oURfAj3COHR63TpCFD0q0JPbO1LFT9HFiMQoTh2gGsXXQNUs/I9Tywa3dfeq8P1UEy5IshUTLGbOOFexdwfjO513sdwT8ngT9CRz+myZQAuBq3MrZy/RlvfPupQN0dqEfaR7FELl25mJnYuQ2gAIm4TsPWlBGzaU5BlCwWeA=
env:
  global:
    - ORGANIZATION=rentpath
    - REPOSITORY=RPValidationKit
    - FRAMEWORK_NAME=$REPOSITORY
    # GITHUB_ACCESS_TOKEN
    - secure: "os7ScLm7k2wXbweDO7PBdYhgEwTPe9PNVwvnWm1Pya2X+T7upAGm0i5YV/aHJsKNih71lGe1Qm177S0RG8mo/7h5a7KxfpgsRtXpJSp7q1PFnfdNN6fvC258jddmx0G1nTtKWaFefG9t67Vj1KujHhZP9rWt1l3IzO5TM1KZa2Iq88PNpOw0q1e/13++fXVN16EELzfgus5SkH7JLqRwWyYbOxfBQvyNkFYN7OKK+grU/PS66l8m1ZQJX6Z0Abf43aCru6WTlOxGOVC0Dk/TmruzGL3fwfw9/XFmc15cUFwprs4kv+TTKL7RgAnNtjZtLWSiBXj2dkGd+0XuYKIUy03RLhBP+mWCNShOLx+NxP/L53X9DTjvLzuz1W3j4KLaiPZOJWuhG9+lHl7b+UtIMMeWAuoESLqTiT6ufyJVdl8X6+We2xQ667LmLlWWnwsX0DFKxbI4B30M68zoZA8D2K/yTxocQisVwwfEBe1/ARTPksORyXlZp3jThPQIvgfoYPSEVOJJyNH8undUIWqbH6pKeIx1Hfo7aVx3wu/KncUFaiIXXcL8UScGytU0YlflByDQlJfACuuQNPXLPKJ9oiR/VrBoHxa7Z0GH3Q0CkNpEnBB8ioyg2AEAbszJPXxTeKlnKg1b4Im1c5wiMDpP9sIqNcEl0Deb95q0AqxqSUM="
    # PIVOTAL_TOKEN
    - secure: "gYiOnVocrjiQ087xsXExS8hD7ODLobbd5kpB18+4IL+nGY6EUMGF+++U4/ONq4lRYOGVhY+ti0F2SacaQAq50YyxOpU8RPyrz6Qm1OVwyXabj5WSkf7JGg7cUm3DOytsqpoEhJYheMc9/otKTi6ltEOm8rNb5qN7QK6kR9Qq1w2gQ+Me6e0o3gLy0auh1kGQAJr36BLYeRabEKmhrCnFHH0lrCo9XMTxd3sTewd6+63In1TKj7OV9LKGP++/VvxyEN0WBhhkkmFVd6K9u35zhaE8ApcKZ8oDcXekJ/lsQkWPo237eFclB4auYv3HN3LGgLPO+ovgVDfEG59hUzEEz2KRslYIFU2aEbaCik3c8h2Th+q5tgCGhdImayEjYVVuO1zXWCFGz+APGpl35drz/Ab60yg4mMi5f199U+/UEx/cNKAjkJ0YRKOQCfMbUpbuuTyEGMPsgzbAmW+29Js3Po2jYyiR7kEL2qJzgC/D4dSxWtLMUWnIU7oAxbz+uH/6JTfhG5xhRVphcSics4Y/AGkcK8QQLO0P+OGV11y6527yi5MadkJWludOpkYz3EO0mCIax6PR50rnpxVS6dzh8GXn5Gmj0szcForgh6yNg93ja+Ff3Dei5g3ybFWOG+QIxverya8caMEH6JPaKxylunnd+ibTDzTdSVzFu+JOxhE="
before_install:
   - brew update
   - brew outdated carthage || brew upgrade carthage

script:
  - fastlane build --env build

after_success:
  - fastlane deploy --env build

deploy:
  provider: releases
  api_key:
    secure: I4399KgIwitMME6T5lSrdJt7C+45XTcT04FWrogPLUs9u7LghyYY+j+PVt4DjxfcvyhJktahYQdpLa803qztoUjVEADGNeBAMWiqKJ/RgNwZttHlAw1ZYsebxe+cIRBVp2HKNA/rE8zVX93xYMl9dOazr5vpp+iNH0L2aVkwND7CdcwBphqVqpkF8Kbw1rqobzZvKgzDMMdwxkWTrvBIn/z/xu3zp8krYwrM/cYsITaACKsprCMmPI+h81O486glmO56NKXQmQGo5zcembaYCRdun3sw/k+AukmYpy0S2pmvfr1aIUNL5Ti8w+Zr4hWkKlpNOelBrb9Z2mu5BVRimKvbO0swIwURXY1ruJUwpNquBhgXEse84bAAgvm7NpRVu+/nKldFRr/9yps19NsBySBI5YayZdAdK72s0LcofnftFtq314S927kGB+6WoivL6h9z4ER+bz6EQ6RzBWpwvxCDcVm1Nc9WEpaygZNyq1GfnfDucq6VJhJd0U25k5Bxrb4uTT2AaT/udaDIII9hxXhro79G5ie0sBGiTqeXwAjP6I490dbMYtfVY7Zkc4JxhJ/0EH3pap5Va+BTIjsXWMOHZPOe1rEX1zWioiP18YW+rjZ1uMLRXzU9l+QNCTHQJX0muq8DKjGkEjrnvJ8rIwBRlJu+bQpOR/2fDXTHmQw=
  file: $REPOSITORY.framework.zip
  skip_cleanup: true
  on:
    repo: $ORGANIZATION/$REPOSITORY
    tags: true
